import { call } from '@arbol/design-system'
export const MERGE_REQUESTS_CORPUS = 'merge-requests'; export const GITLAB_MIRROR_CORPUS = 'mirrors/gitlab'
export type MergeRequest = { id: string; title: string; project: string; iid: number; url: string; state: string; author: string; sourceBranch: string; targetBranch: string; updated: string; changedFiles: number; sourcePath: string }
type Node = { path: string; type: 'dir' | 'file'; children?: Node[] }; type Tree = { tree: Node[] }; type Rpc = (method: string, params?: Record<string, unknown>) => Promise<unknown>; type RecordValue = Record<string, unknown>
const asRecord = (value: unknown): RecordValue => value !== null && typeof value === 'object' && !Array.isArray(value) ? value as RecordValue : {}; const text = (value: unknown) => typeof value === 'string' ? value.trim() : ''; const files = (nodes: Node[]): string[] => nodes.flatMap((node) => node.type === 'file' ? [node.path] : files(node.children ?? []))
function frontmatter(content: string): Record<string, string> { const match = /^---\s*\n([\s\S]*?)\n---/m.exec(content); if (!match) return {}; return Object.fromEntries(match[1].split('\n').flatMap((line) => { const index = line.indexOf(':'); if (index < 1) return []; return [[line.slice(0, index).trim(), line.slice(index + 1).trim().replace(/^"|"$/g, '')]] })) }
function fromNormalized(path: string, content: string): MergeRequest | null { const meta = frontmatter(content); const project = text(meta.project); const iid = Number(meta.iid); if (!project || !Number.isInteger(iid)) return null; const heading = /^#\s+.+?:\s*(.+)$/m.exec(content)?.[1]?.trim(); return { id: `${project}!${iid}`, project, iid, title: heading || text(meta.title) || `Merge request !${iid}`, url: text(meta.url), state: text(meta.state), author: text(meta.author), sourceBranch: text(meta.source_branch), targetBranch: text(meta.target_branch), updated: text(meta.updated), changedFiles: (content.match(/^[-*] .+$/gm) ?? []).length, sourcePath: path } }
export async function loadMergeRequests(rpc: Rpc = call): Promise<MergeRequest[]> { const tree = asRecord(await rpc('artifacts.tree', { repo: MERGE_REQUESTS_CORPUS })) as unknown as Tree; const paths = files(tree.tree ?? []).filter((path) => path.endsWith('.md')); if (!paths.length) return []; const response = asRecord(await rpc('artifacts.read_many', { repo: MERGE_REQUESTS_CORPUS, paths })); const records = Array.isArray(response.files) ? response.files.map(asRecord) : []; return records.flatMap((file) => { const item = fromNormalized(text(file.path), text(file.content)); return item ? [item] : [] }).sort((a, b) => b.updated.localeCompare(a.updated) || a.id.localeCompare(b.id)) }
export async function importMergeRequest(url: string, rpc: Rpc = call): Promise<void> { const result = asRecord(await rpc('quick_input.submit', { content: url, force_refresh: true })); if (result.handled !== true || text(asRecord(result.classification).input_type) !== 'gitlab.merge_request') throw new Error(text(result.message) || 'Could not import merge request') }
/** Re-fetches this MR through the same durable GitLab-mirror pipeline as import. */
export async function syncMergeRequest(item: MergeRequest, rpc: Rpc = call): Promise<void> { if (!item.url) throw new Error('This merge request has no GitLab URL to sync'); await importMergeRequest(item.url, rpc) }

export type FetchMyOpenMergeRequestsResult = { projects: string[]; matched: number; fetched: number; failed: number; failures: { merge_request: string; error: string }[]; message: string }
export async function fetchMyOpenMergeRequests(rpc: Rpc = call): Promise<FetchMyOpenMergeRequestsResult> { return asRecord(await rpc('gitlab.fetch_my_open_merge_requests', {})) as unknown as FetchMyOpenMergeRequestsResult }
