import { strict as assert } from 'node:assert'
import { chromium } from 'playwright'
import { createServer } from 'vite'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../../..')
const server = await createServer({ root, configFile: resolve(root, 'apps/elma/vite.config.ts'),
  server: { host: '127.0.0.1', port: 0 }, logLevel: 'error' })
let browser
try {
  await server.listen()
  browser = await chromium.launch({ headless: true, ...(process.env.ARBOL_BROWSER_CHANNEL ? { channel: process.env.ARBOL_BROWSER_CHANNEL } : {}) })
  const page = await browser.newPage()
  const errors = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto(`http://127.0.0.1:${server.httpServer.address().port}/apps/elma/e2e/activity-graph-fixture.html`)
  await page.getByText('Activity 1: first.activity', { exact: true }).waitFor()
  await page.getByText('Activity 2: first.activity', { exact: true }).click()
  await page.getByText('Caused by: Activity 1', { exact: true }).waitFor()
  assert.match(await page.getByRole('region', { name: 'Activity Graph' }).innerText(), /Value from Activity 1/)
  const refreshing = page.getByText(/Refreshing Activity history… Showing a stale/ )
  const refreshButton = page.getByRole('button', { name: 'Refresh Activities' })
  const waitIdle = () => page.waitForFunction(() => document.querySelector('.activity-graph')?.getAttribute('aria-busy') === 'false')
  const expanded = () => page.locator('details').nth(1).evaluate(node => node.open)
  const beforeHints = await page.evaluate(() => window.activityRequests.length)
  await page.evaluate(() => window.invalidateActivity('completed', 100))
  await refreshing.waitFor()
  assert.equal(await expanded(), true)
  await waitIdle()
  assert.equal(await expanded(), true)
  assert.match(await page.locator('summary').nth(1).innerText(), /completed/)
  assert.equal(await page.evaluate(() => window.activityRequests.length), beforeHints + 1)
  assert.equal(await page.evaluate(() => window.activityStreamCount()), 1)
  await page.evaluate(() => window.reconnectActivity())
  await refreshing.waitFor()
  await waitIdle()
  assert.equal(await expanded(), true)
  assert.equal(await page.evaluate(() => window.activityStreamCount()), 2)
  // Several invalidated IO cycles never remove the last accepted graph or its DOM.
  let expectedReads = await page.evaluate(() => window.activityRequests.length)
  await page.evaluate(() => window.configureActivity({ hold: true }))
  for (let i = 0; i < 3; i++) {
    await page.evaluate(() => window.invalidateActivity('failed'))
    await page.waitForFunction(count => window.activityRequests.length === count, ++expectedReads)
    await page.evaluate(() => { window.invalidateActivity('failed', 100); window.releaseActivity() })
    await refreshing.waitFor()
    assert.equal(await expanded(), true)
    assert.match(await page.locator('summary').nth(1).innerText(), /completed/)
  }
  await page.evaluate(() => window.configureActivity({}))
  await waitIdle()
  assert.match(await page.locator('summary').nth(1).innerText(), /failed/)
  assert.equal(await expanded(), true)
  for (const outcome of ['unavailable', 'error']) {
    await page.evaluate(outcome => window.configureActivity({ outcome }), outcome)
    await refreshButton.click()
    await page.getByText(/Activity history refresh unavailable. Showing a stale/).waitFor()
    assert.equal(await expanded(), true)
    const failedReads = await page.evaluate(() => window.activityRequests.length)
    await page.waitForTimeout(350)
    assert.equal(await page.evaluate(() => window.activityRequests.length), failedReads)
  }
  await page.evaluate(() => window.configureActivity({}))
  await refreshButton.click()
  await waitIdle()
  assert.equal(await page.getByText(/Showing a stale/).count(), 0)
  assert.equal(await expanded(), true)
  // An accepted empty observation removes stale nodes; returning nodes start closed.
  await page.evaluate(() => window.configureActivity({ empty: true }))
  await refreshButton.click()
  await page.getByText('No canonical Activity executions in this observed Exchange range.').waitFor()
  assert.equal(await page.locator('details').count(), 0)
  await page.evaluate(() => window.configureActivity({}))
  await refreshButton.click()
  await page.getByText('Activity 2: first.activity', { exact: true }).waitFor()
  assert.equal(await expanded(), false)
  await page.getByText('Activity 2: first.activity', { exact: true }).click()

  await page.getByRole('button', { name: 'Select slow Exchange' }).click()
  await page.getByText('Loading Activity history…').waitFor()
  await page.getByRole('button', { name: 'Select second Exchange' }).click()
  // A selection change never overlaps the unreturned graph read.
  await page.evaluate(() => window.releaseActivity())
  await page.getByText('Activity 1: second.activity', { exact: true }).waitFor()
  assert.equal(await expanded(), false) // Same execution IDs, different Exchange.
  await page.waitForTimeout(100)
  assert.equal(await page.getByText('Activity 1: slow.activity', { exact: true }).count(), 0)
  await page.getByRole('button', { name: 'Select empty Exchange' }).click()
  await page.getByText('No canonical Activity executions in this observed Exchange range.').waitFor()
  await page.getByRole('button', { name: 'Select unavailable Exchange' }).click()
  await page.getByText('Activity history unavailable or beyond inspection limits. Refresh to try again.').waitFor()
  await page.getByRole('button', { name: 'Select slow Exchange' }).click()
  await page.getByText('Loading Activity history…').waitFor()
  await page.getByRole('button', { name: 'Close Thread Inspector' }).click()
  await page.evaluate(() => window.releaseActivity())
  assert.equal(await page.getByRole('region', { name: 'Activity Graph' }).count(), 0)
  const countAtClose = await page.evaluate(() => window.activityRequests.length)
  await page.evaluate(() => window.invalidateActivity('failed', 100))
  await page.waitForTimeout(350)
  assert.equal(await page.evaluate(() => window.activityRequests.length), countAtClose)
  await page.evaluate(() => window.stopActivityView())
  const requests = await page.evaluate(() => window.activityRequests)
  assert.ok(requests.length >= 7)
  assert.ok(requests.every(r => r.method === 'activity_graph.get' && r.params.chat_session_id === 'session'))
  assert.deepEqual(errors, [])
  console.log('Activity Graph browser checks passed: rendering, links, coalesced/sustained live refresh, stale failure state, expansion continuity/reset, reconnect, manual refresh, empty/unavailable, stale response, unmount; RPC transport stubbed')
} finally { if (browser) await browser.close(); await server.close() }
