// renderer/packages/events/src/catalog.gen.ts
// GENERATED by tools/gen_event_types.py — DO NOT EDIT BY HAND.
// Source of truth: daemons/shared/arbol_shared/events/catalog.py
// Regenerate:      python tools/gen_event_types.py   (build.sh/CI fail on drift)

export type ThinkingLevel = 'none' | 'minimum' | 'medium' | 'high' | 'xhigh' | 'max' | 'ultra'
export type AgentTurnInputKind = 'exchange_message' | 'tool_results' | 'permission_response'
export type AgentTurnStopReason = 'waiting_for_tool_results' | 'waiting_for_permission' | 'completed' | 'failed' | 'cancelled'
export type ToolDecision = 'run' | 'run_always' | 'reject'
export type SurfaceKind = 'ui' | 'cli' | 'api' | 'integration' | 'internal'
export type SubmissionKind = 'initial_message' | 'reply' | 'edit_replacement'

export type Actor = 'core' | 'effector' | 'user' | `ip:${string}`

export interface ToolRequestRef { id: string; kind: string; params: Record<string, unknown> }
export interface MessageAttachment { type: string; mime_type: string; data: string; name?: string; size?: number }
export interface TokenUsage { model: string; tokens_in: number; tokens_out: number; cost_usd: number }
export interface RouteDecision { ip_name: string; reason: string }
export interface SurfaceRef { kind: SurfaceKind; name: string }
export interface RequestedTurnOptions { ip_name?: string; model?: string; thinking_level?: ThinkingLevel }
export interface WorkspaceScope { primary_repository?: string; workspace_dirs: string[] }
export interface AttachmentRef { sha256: string; mime_type: string; byte_len: number; filename?: string }
export interface ActivityValueIdentity { name: string; value_id: string; kind: string }
export interface ActivityFailureIdentity { failure_id: string; code: string; message: string }
export interface ActivityCancellationIdentity { cancellation_id: string; reason: string }

export interface EventEnvelope {
  seq: number
  chat_session_seq: number
  id: string
  ts: number
  aggregate: string
  aggregate_id: string
  correlation_id: string | null
  causation_id: string | null
  actor: Actor
}

export type ArbolEvent = EventEnvelope & (
  | { type: 'CHAT_SESSION_CREATED'; v: 1; payload: { title?: string; ip_name?: string; model?: string; thinking_level?: ThinkingLevel; fast_mode?: boolean; workspace_dirs: string[]; worktree_path?: string; initiator_kind?: string; parent_chat_session_id?: string; initiator_id?: string; initiating_mandate_id?: string; initiating_mandate_version_id?: string; initiating_activation_rule_id?: string; activation_signal_id?: string; steward_run_id?: string } }
  | { type: 'CHAT_SESSION_RENAMED'; v: 1; payload: { title: string } }
  | { type: 'CHAT_SESSION_DRAFT_STARTED'; v: 1; payload: Record<string, never> }
  | { type: 'CHAT_SESSION_DRAFT_CLEARED'; v: 1; payload: Record<string, never> }
  | { type: 'CHAT_SESSION_ARCHIVED'; v: 1; payload: Record<string, never> }
  | { type: 'CHAT_SESSION_SET_THINKING_LEVEL'; v: 1; payload: { thinking_level: ThinkingLevel } }
  | { type: 'CHAT_SESSION_SET_MODEL'; v: 1; payload: { model: string } }
  | { type: 'CHAT_SESSION_SET_FAST_MODE'; v: 1; payload: { fast_mode: boolean } }
  | { type: 'CHAT_SESSION_SET_ONGOING'; v: 1; payload: { onGoing: boolean } }
  | { type: 'CHAT_SESSION_SET_UNREAD'; v: 1; payload: { isUnread: boolean } }
  | { type: 'CHAT_SESSION_SET_WORKTREE'; v: 1; payload: { worktree_path: string } }
  | { type: 'USER_ADDED_CHAT_NOTE'; v: 1; payload: { message_id: string; content: string; parent_turn_id?: string; surface?: SurfaceRef } }
  | { type: 'USER_SENT_MESSAGE'; v: 1; payload: { turn_id: string; exchange_id?: string; message_id: string; content: string; thinking_level?: ThinkingLevel; model?: string; parent_turn_id?: string; attachments?: MessageAttachment[]; attachment_refs?: AttachmentRef[]; submission_id?: string; surface?: SurfaceRef; trunk_runtime_id?: string; submission_kind?: SubmissionKind; created_chat_session?: boolean; chat_note_count?: number; workspace_scope?: WorkspaceScope; requested_options?: RequestedTurnOptions } }
  | { type: 'TURN_STARTED'; v: 1; payload: { turn_id: string; ip_name: string } }
  | { type: 'AGENT_TURN_STARTED'; v: 1; payload: { agent_turn_id: string; exchange_id: string; attempt_id: string; input_kind: AgentTurnInputKind; input_id: string } }
  | { type: 'AGENT_TURN_STOPPED'; v: 1; payload: { agent_turn_id: string; exchange_id: string; attempt_id: string; reason: AgentTurnStopReason } }
  | { type: 'ACTIVITY_EXECUTION_READY'; v: 1; payload: { execution_id: string; activity_id: string; trunk_runtime_id: string; exchange_id: string; caused_by_execution_ids: string[]; inputs: ActivityValueIdentity[] } }
  | { type: 'ACTIVITY_EXECUTION_STARTED'; v: 1; payload: { execution_id: string; activity_id: string; trunk_runtime_id: string; exchange_id: string } }
  | { type: 'ACTIVITY_EXECUTION_COMPLETED'; v: 1; payload: { execution_id: string; activity_id: string; trunk_runtime_id: string; exchange_id: string; outputs: ActivityValueIdentity[] } }
  | { type: 'ACTIVITY_EXECUTION_FAILED'; v: 1; payload: { execution_id: string; activity_id: string; trunk_runtime_id: string; exchange_id: string; failure: ActivityFailureIdentity } }
  | { type: 'ACTIVITY_EXECUTION_CANCELLED'; v: 1; payload: { execution_id: string; activity_id: string; trunk_runtime_id: string; exchange_id: string; cancellation: ActivityCancellationIdentity } }
  | { type: 'IP_COMPLETED_CYCLE'; v: 1; payload: { turn_id: string; message_id: string; content: string; thinking?: string } }
  | { type: 'TURN_COMPLETED'; v: 1; payload: { turn_id: string; stop_reason: string } }
  | { type: 'TURN_FAILED'; v: 1; payload: { turn_id: string; error: string; attempts: number } }
  | { type: 'USER_CANCELLED_TURN'; v: 1; payload: { turn_id: string } }
  | { type: 'USER_REMOVED_TURN'; v: 1; payload: { turn_id: string } }
  | { type: 'CORE_SELECTED_IP'; v: 1; payload: { turn_id: string; route: RouteDecision } }
  | { type: 'CORE_RETRIED_FAILOVER'; v: 1; payload: { turn_id: string; from_ip: string; to_ip?: string; attempt: number; reason: string } }
  | { type: 'TURN_FAILED_RATE_LIMIT'; v: 1; payload: { turn_id: string; ip_name: string; recovery_hint_seconds?: number; reason: string } }
  | { type: 'IP_REQUESTED_TOOLS'; v: 1; payload: { turn_id: string; batch_id: string; requests: ToolRequestRef[] } }
  | { type: 'TOOL_REQUEST_OPENED'; v: 1; payload: { request_id: string; batch_id: string; kind: string; params: Record<string, unknown>; origin?: string; tool_use_id?: string; ask_id?: string; tool_name?: string; tool_input?: Record<string, unknown> } }
  | { type: 'TOOL_REQUEST_AWAITING_APPROVAL'; v: 1; payload: { request_id: string; reason?: string; canonical_kind: string; approval_policy: string } }
  | { type: 'USER_DECIDED_TOOL_REQUEST'; v: 1; payload: { request_id: string; decision: ToolDecision; reason?: string; answers?: Record<string, unknown> } }
  | { type: 'TOOL_REQUEST_TIMED_OUT'; v: 1; payload: { request_id: string; reason?: string } }
  | { type: 'EFFECTOR_SETTLED_TOOL_REQUEST'; v: 1; payload: { request_id: string; ok: boolean; result?: Record<string, unknown>; error?: string; content_ref?: Record<string, unknown>; content_format?: string } }
  | { type: 'IP_INVOKED_NATIVE_TOOL'; v: 1; payload: { turn_id: string; tool_use_id: string; tool_name: string; input: Record<string, unknown>; request_id?: string } }
  | { type: 'IP_SETTLED_NATIVE_TOOL'; v: 1; payload: { turn_id: string; tool_use_id: string; ok: boolean; result?: Record<string, unknown>; error?: string; content_ref?: Record<string, unknown>; content_format?: string } }
  | { type: 'TURN_RECORDED_USAGE'; v: 1; payload: { turn_id: string; subscription_name?: string; usage: TokenUsage } }
  | { type: 'SUBSCRIPTION_LOGGED_IN'; v: 1; payload: { subscription_name: string; provider: string } }
  | { type: 'SUBSCRIPTION_LOGGED_OUT'; v: 1; payload: { subscription_name: string } }
  | { type: 'SUBSCRIPTION_AUTH_EXPIRED'; v: 1; payload: { subscription_name: string } }
  | { type: 'SUBSCRIPTION_CAPTURED_USAGE'; v: 1; payload: { subscription_name: string; metrics: Record<string, unknown> } }
  | { type: 'CORE_RAISED_ERROR'; v: 1; payload: { scope: string; message: string; detail?: Record<string, unknown> } }
)

export type TransientFrame =
  | { type: 'assistant.text_delta'; v: 1; payload: { turn_id: string; text: string } }
  | { type: 'assistant.thinking_delta'; v: 1; payload: { turn_id: string; thinking: string } }
  | { type: 'usage.tick'; v: 1; payload: { turn_id: string; partial: TokenUsage } }
  | { type: 'tool_request_output'; v: 1; payload: { request_id: string; stream: string; text: string } }
  | { type: 'turn.rate_limit_wait'; v: 1; payload: { turn_id: string; ip_name: string; retry_at: number; recovery_seconds: number } }
